[build]
  publish = "."

# Form success redirect
[[redirects]]
  from = "/success"
  to = "/thanks.html"
  status = 302

# Correct path for the thanks page
[[redirects]]
  from = "/thanks.html"
  to = "/thanks.html"
  status = 200

# Default fallback 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

# Form handling settings
[build.processing.html]
  pretty_urls = true 